root: true
parser: '@typescript-eslint/parser'
env:
  browser: true
  es6: true
  node: true
plugins:
  - '@typescript-eslint'
  - svelte3
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
  - prettier
overrides:
  - files:
    - '*.js'
    - '*.ts'
  - files:
    - '*.svelte'
    processor: svelte3/svelte3
    # Svelte/Eslint/TS currently have [some limitations](https://github.com/sveltejs/eslint-plugin-svelte3#installation-with-typescript).
    # Therefore the following rules are disabled as they are caught by typescript anyway.
    rules:
      '@typescript-eslint/no-unsafe-assignment': 'off'
      '@typescript-eslint/no-unsafe-call': 'off'
      '@typescript-eslint/no-unsafe-member-access': 'off'
      'no-undef': 'off'
settings:
  svelte3/typescript: true
parserOptions: 
  ecmaVersion: 2019
  sourceType: module
  tsconfigRootDir: .
  project: ['./tsconfig.json']
  extraFileExtensions: ['.svelte']

